# .claude-code.yml
auto_approve:
  file_create: true
  file_edit: true
  file_delete: false # Keep this manual for safety
  command_execution: true

allowed_commands:
  - cargo build
  - cargo test
  - cargo run
  - cargo fmt
  - cargo clippy

allowed_paths:
  - "src/**"
  - "tests/**"
  - "Cargo.toml"
  - "Cargo.lock"

restricted_paths:
  - ".git/**"
  - "target/**" # Don't edit build artifacts
